import BlogContext from "./BlogContext";

const BlogState = (props) => {
  const company = "IGCSM";
  const news =
    "INDIA NO. -1 FRANCHISEE NETWORK - IGCSM FRANCHISEE. JOIN TODAY INDIA'S LARGEST COMPUTER TRAINING AND SKILL CERTIFICATE NETWORK.   ONLINE EXAM | ONLINE SUPPORT | ONLINE VERIFICATION";
 
  const states = {
    records: [
      {
        state_code: 20,
        state_name_english: "Jharkhand",
        state_name_local: "झारखंड",
        state_census2011_code: "20",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 37,
        state_name_english: "Ladakh",
        state_name_local: "Ladakh",
        state_census2011_code: "00",
        state_or_ut: "U",
        last_updated: "2024-08-16",
      },
      {
        state_code: 23,
        state_name_english: "Madhya Pradesh",
        state_name_local: "MADHYA PRADESH                                    ",
        state_census2011_code: "23",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 17,
        state_name_english: "Meghalaya",
        state_name_local: "MEGHALAYA                                         ",
        state_census2011_code: "17",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 3,
        state_name_english: "Punjab",
        state_name_local: "PUNJAB                                            ",
        state_census2011_code: "03",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 11,
        state_name_english: "Sikkim",
        state_name_local: "SIKKIM                                            ",
        state_census2011_code: "11",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 38,
        state_name_english: "The Dadra And Nagar Haveli And Daman And Diu",
        state_name_local: "THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU",
        state_census2011_code: "NA",
        state_or_ut: "U",
        last_updated: "2024-08-16",
      },
      {
        state_code: 9,
        state_name_english: "Uttar Pradesh",
        state_name_local: "UTTAR PRADESH                                     ",
        state_census2011_code: "09",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 19,
        state_name_english: "West Bengal",
        state_name_local: "WEST BENGAL                                       ",
        state_census2011_code: "19",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 28,
        state_name_english: "Andhra Pradesh",
        state_name_local: "ANDHRA PRADESH                                    ",
        state_census2011_code: "28",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 12,
        state_name_english: "Arunachal Pradesh",
        state_name_local: "ARUNACHAL PRADESH                                 ",
        state_census2011_code: "12",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 10,
        state_name_english: "Bihar",
        state_name_local: "BIHAR                                             ",
        state_census2011_code: "10",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 4,
        state_name_english: "Chandigarh",
        state_name_local: "CHANDIGARH                                        ",
        state_census2011_code: "04",
        state_or_ut: "U",
        last_updated: "2024-08-16",
      },
      {
        state_code: 22,
        state_name_english: "Chhattisgarh",
        state_name_local: "छत्तीसगढ़",
        state_census2011_code: "22",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 27,
        state_name_english: "Maharashtra",
        state_name_local: "महाराष्ट्र",
        state_census2011_code: "27",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 14,
        state_name_english: "Manipur",
        state_name_local: "MANIPUR                                           ",
        state_census2011_code: "14",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 36,
        state_name_english: "Telangana",
        state_name_local: "తెలంగాణ",
        state_census2011_code: "00",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 18,
        state_name_english: "Assam",
        state_name_local: "ASSAM                                             ",
        state_census2011_code: "18",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 24,
        state_name_english: "Gujarat",
        state_name_local: "GUJARAT                                           ",
        state_census2011_code: "24",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 2,
        state_name_english: "Himachal Pradesh",
        state_name_local: "HIMACHAL PRADESH                                  ",
        state_census2011_code: "02",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 29,
        state_name_english: "Karnataka",
        state_name_local: "ಕರ್ನಾಟಕ",
        state_census2011_code: "29",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 31,
        state_name_english: "Lakshadweep",
        state_name_local: "LAKSHADWEEP                                       ",
        state_census2011_code: "31",
        state_or_ut: "U",
        last_updated: "2024-08-16",
      },
      {
        state_code: 21,
        state_name_english: "Odisha",
        state_name_local: "ODISHA",
        state_census2011_code: "21",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 34,
        state_name_english: "Puducherry",
        state_name_local: "PUDUCHERRY",
        state_census2011_code: "34",
        state_or_ut: "U",
        last_updated: "2024-08-16",
      },
      {
        state_code: 35,
        state_name_english: "Andaman And Nicobar Islands",
        state_name_local: "ANDAMAN AND NICOBAR ISLANDS                       ",
        state_census2011_code: "35",
        state_or_ut: "U",
        last_updated: "2024-08-16",
      },
      {
        state_code: 7,
        state_name_english: "Delhi",
        state_name_local: "DELHI                                             ",
        state_census2011_code: "07",
        state_or_ut: "U",
        last_updated: "2024-08-16",
      },
      {
        state_code: 30,
        state_name_english: "Goa",
        state_name_local: "GOA                                               ",
        state_census2011_code: "30",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 6,
        state_name_english: "Haryana",
        state_name_local: "HARYANA                                           ",
        state_census2011_code: "06",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 1,
        state_name_english: "Jammu And Kashmir",
        state_name_local: "JAMMU AND KASHMIR",
        state_census2011_code: "01",
        state_or_ut: "U",
        last_updated: "2024-08-16",
      },
      {
        state_code: 32,
        state_name_english: "Kerala",
        state_name_local: "KERALA                                            ",
        state_census2011_code: "32",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 15,
        state_name_english: "Mizoram",
        state_name_local: "MIZORAM                                           ",
        state_census2011_code: "15",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 13,
        state_name_english: "Nagaland",
        state_name_local: "NAGALAND                                          ",
        state_census2011_code: "13",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 8,
        state_name_english: "Rajasthan",
        state_name_local: "RAJASTHAN                                         ",
        state_census2011_code: "08",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 33,
        state_name_english: "Tamil Nadu",
        state_name_local: "TAMIL NADU                                        ",
        state_census2011_code: "33",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 16,
        state_name_english: "Tripura",
        state_name_local: "ত্রিপুরা",
        state_census2011_code: "16",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
      {
        state_code: 5,
        state_name_english: "Uttarakhand",
        state_name_local: "UTTARAKHAND",
        state_census2011_code: "05",
        state_or_ut: "S",
        last_updated: "2024-08-16",
      },
    ],
  };

  return (
    <BlogContext.Provider
      // value here which we want to export
      value={{
        company,
        news,
        states,
      }}
    >
      {props.children}
    </BlogContext.Provider>
  );
};

export default BlogState;
